# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2024 Analog Devices, Inc.

obj-y   += soc.o
obj-y   += lowlevel_init.o
obj-y   += adrv906x_fdt.o
obj-y	+= adrv906x_status_reg.o
obj-y   += adrv_common.o
obj-y	+= err.o

