# SPDX-License-Identifier: GPL-2.0-or-later
#
# (C) Copyright 2022 - Analog Devices, Inc.
#
# Written by Timesys Corporation
#

obj-y = clkinit.o

obj-$(CONFIG_SC846) += EHP2_LP4_1D_2000/
obj-$(CONFIG_SC5XX_DMC_INIT) += dmcinit.o
