name: Build U-Boot for 64-bit ARM

on:
  workflow_call:
    inputs:
      defconfig:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install aarch64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install ADSP LDR
        run: |
          sudo apt-get install -y libusb-1.0-0-dev
          pip install meson
          curl -LO https://github.com/analogdevicesinc/adsp-ldr/releases/download/v1.0.1/adsp-ldr-v1.0.1.tar.xz
          tar -xf adsp-ldr-v1.0.1.tar.xz
          cd adsp-ldr-v1.0.1
          meson setup builddir
          cd builddir
          meson install
          ln -s /usr/local/bin/ldr /usr/local/bin/aarch64-linux-gnu-ldr

      - name: Build U-Boot
        run: |
          echo ${PATH}
          export CROSS_COMPILE="aarch64-linux-gnu-"
          sudo apt-get install -y uuid-dev
          make ${{ inputs.defconfig }}
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: u-boot-${{ inputs.defconfig }}
          path: |
            u-boot
            u-boot.elf
            u-boot.bin
            u-boot.ldr
            spl/u-boot-spl
            spl/u-boot-spl.bin
            spl/u-boot-spl.ldr
          retention-days: 7
