name: Build U-Boot for 32-bit ARM

on:
  workflow_call:
    inputs:
      defconfig:
        required: true
        type: string

jobs:
  build:
    uses: analogdevicesinc/u-boot/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      arch: arm
      defconfig: ${{ inputs.defconfig }}

