name: Build U-Boot

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Architecture (arm, arm64)"
        required: true
        type: string
      defconfig:
        description: "Defconfig (sc584-ezkit_defconfig, ...)"
        required: true
        type: string
      ref:
        required: true
        default: "refs/heads/adi-u-boot-2025.10.y"
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      defconfig:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgnutls28-dev \
            device-tree-compiler uuid-dev \
            libusb-1.0-0
          if [[ "${{ inputs.arch }}" == "arm" ]]; then
            sudo apt-get install -y gcc-arm-none-eabi
          elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi

      - name: Install ADSP LDR
        run: |
          curl -LO https://packages.analog.com/public/deb/ubuntu/pool/any-version/main/a/ad/adsp-ldr_1.0.2/adsp-ldr_1.0.2_amd64.deb
          sudo apt-get install -y ./adsp-ldr_1.0.2_amd64.deb

          if [[ "${{ inputs.arch }}" == "arm" ]]; then
            sudo ln -s /usr/bin/ldr /usr/bin/arm-none-eabi-ldr
          elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
            sudo ln -s /usr/bin/ldr /usr/bin/aarch64-linux-gnu-ldr
          fi

      - name: Build U-Boot
        run: |
          echo ${PATH}
          if [[ "${{ inputs.arch }}" == "arm" ]]; then
            export CROSS_COMPILE="arm-none-eabi-"
          elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
            export CROSS_COMPILE="aarch64-linux-gnu-"
          fi
          make "${{ inputs.defconfig }}"
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.defconfig }}
          path: |
            u-boot
            u-boot.elf
            u-boot.bin
            u-boot.ldr
            spl/u-boot-spl
            spl/u-boot-spl.bin
            spl/u-boot-spl.ldr
          retention-days: 7

  deploy_cloudsmith:
    needs: [build]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      artifacts: >
        *
