name: Checks

on:
  workflow_call:
    inputs:
      strategy:
        required: false
        type: string
        default: "commit" # when supported, or "file"
      checkpatch_extraignores:
        type: string
        default: ""
    outputs:
      fatal:
        value: ${{ jobs.checks.outputs.fatal}}
      summary:
        value: ${{ jobs.checks.outputs.summary }}

jobs:
  checks:
    timeout-minutes: 7200
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    continue-on-error: true

    outputs:
      fatal: ${{ steps.assert.outputs.fatal }}
      summary: ${{ steps.assert.outputs.summary }}

    steps:
    - uses: analogdevicesinc/doctools/checkout@action

    - name: Get sources
      run: |
        get_file () {
          echo https://raw.githubusercontent.com/analogdevicesinc/u-boot/refs/heads/ci/$1
          curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $1 \
              https://raw.githubusercontent.com/analogdevicesinc/u-boot/refs/heads/ci/$1
        }

        mkdir -p ci
        get_file ci/build.sh
        get_file ci/runner_env.sh
        get_file ci/buildman
        cp ci/buildman ~/.buildman

    - name: Install dependencies
      if: ${{ runner.environment == 'github-hosted' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-none-eabi \
          gcc-aarch64-linux-gnu

    - name: Apply cocci
      run: |
        source ./ci/build.sh
        apply_prerun

    - name: Assert state
      if: ${{ failure() }}
      run: |
        source ./ci/build.sh
        set_step_fail "assert_state"
        echo "fatal=true" >> "$GITHUB_ENV"

    - name: License
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        source ./ci/build.sh
        check_license

    - name: Check patch
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        export CHECKPATCH_EXTRAIGNORES="${{ inputs.checkpatch_extraignores }}";
        status=0; timeout 1d bash -c "source ./ci/build.sh ; check_checkpatch ${{ inputs.strategy }}" || status=$?
        [ $status -eq 124 ] && echo "step_fail_checkpatch_timeout=true" >> "$GITHUB_ENV"
        exit $status

    - name: Coccicheck
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        status=0; timeout 1d bash -c "source ./ci/build.sh ; check_coccicheck" || status=$?
        [ $status -eq 124 ] && echo "step_fail_coccicheck_timeout=true" >> "$GITHUB_ENV"
        exit $status

    - name: Check qconfig
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        command -v yq
        configs="$(yq -r '.jobs[]
                    | select(.uses == "analogdevicesinc/u-boot/.github/workflows/build.yml@*")
                    | (.with.defconfig, (.strategy.matrix.defconfig[]?))
                    | select(. != null and . != "$" + "{{ matrix.defconfig }}")
                  ' .github/workflows/top-level.yml)"
        source ./ci/build.sh
        check_qconfig_sync ${configs[@]}

    - name: Export labels
      if: ${{ !cancelled() }}
      id: assert
      run: |
        echo "fatal=$fatal" >> "$GITHUB_OUTPUT"
        source ./ci/runner_env.sh
        export_job_summary
