name: Checks

on:
  workflow_call:
    inputs:
      strategy:
        required: false
        type: string
        default: "commit" # when supported, or "file"
      checkpatch_extraignores:
        type: string
        default: ""
      defconfigs:
        required: false
        type: string
        default: ""
    outputs:
      fatal:
        value: ${{ jobs.checks.outputs.fatal}}
      summary:
        value: ${{ jobs.checks.outputs.summary }}

jobs:
  checks:
    timeout-minutes: 7200
    runs-on: [self-hosted, repo-only, v4]
    continue-on-error: true

    outputs:
      fatal: ${{ steps.assert.outputs.fatal }}
      summary: ${{ steps.assert.outputs.summary }}

    steps:
    - uses: analogdevicesinc/doctools/checkout@action

    - name: Get sources
      run: |
        get_file () {
          echo https://raw.githubusercontent.com/analogdevicesinc/u-boot/refs/heads/ci/$1
          curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $1 \
              https://raw.githubusercontent.com/analogdevicesinc/u-boot/refs/heads/ci/$1
        }

        mkdir -p ci
        get_file ci/build.sh
        get_file ci/runner_env.sh

    - name: Apply cocci
      run: |
        source ./ci/build.sh
        apply_prerun

    - name: Assert state
      if: ${{ failure() }}
      run: |
        source ./ci/build.sh
        set_step_fail "assert_state"
        echo "fatal=true" >> "$GITHUB_ENV"

    - name: License
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        source ./ci/build.sh
        check_license

    - name: Check patch
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        export CHECKPATCH_EXTRAIGNORES="${{ inputs.checkpatch_extraignores }}";
        status=0; timeout 1d bash -c "source ./ci/build.sh ; check_checkpatch ${{ inputs.strategy }}" || status=$?
        [ $status -eq 124 ] && echo "step_fail_checkpatch_timeout=true" >> "$GITHUB_ENV"
        exit $status

    - name: Coccicheck
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        status=0; timeout 1d bash -c "source ./ci/build.sh ; check_coccicheck" || status=$?
        [ $status -eq 124 ] && echo "step_fail_coccicheck_timeout=true" >> "$GITHUB_ENV"
        exit $status

    - name: Configure buildman toolchains
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        arm_gcc=$(basename "$(find /opt/gcc/armv7-eabihf/bin -maxdepth 1 -name '*gcc' | head -n 1)")
        aarch64_gcc=$(basename "$(find /opt/gcc/aarch64/bin -maxdepth 1 -name '*gcc' | head -n 1)")

        arm_prefix="/opt/gcc/armv7-eabihf/bin/${arm_gcc%gcc}"
        aarch64_prefix="/opt/gcc/aarch64/bin/${aarch64_gcc%gcc}"

        cat > "$HOME/.buildman" <<EOF
        [toolchain-prefix]
        arm = $arm_prefix
        aarch64 = $aarch64_prefix
        EOF

    - name: Check qconfig
      if: ${{ !cancelled() && env.fatal != 'true' }}
      run: |
        source ./ci/build.sh
        list=$(mktemp)
        cat > "$list" <<'EOF'
        ${{ inputs.defconfigs }}
        EOF
        check_qconfig "$list"

    - name: Export labels
      if: ${{ !cancelled() }}
      id: assert
      run: |
        echo "fatal=$fatal" >> "$GITHUB_OUTPUT"
        source ./ci/runner_env.sh
        export_job_summary
