name: U-Boot CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "adi-u-boot-2025.10.y" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_arm:
    uses: analogdevicesinc/u-boot/.github/workflows/build-arm.yml@ci
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc573-ezlite_defconfig'
          - 'sc584-ezkit_defconfig'
          - 'sc589-ezkit_defconfig'
          - 'sc589-mini_defconfig'
          - 'sc594-som-ezkit-spl_defconfig'
          - 'sc594-som-ezlite-spl_defconfig'

  build_aarch64:
    uses: analogdevicesinc/u-boot/.github/workflows/build-aarch64.yml@ci
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc598-htol-spl_defconfig'
          - 'sc598-som-ezkit-spl_defconfig'
          - 'sc598-som-ezlite-spl_defconfig'
          - 'xilinx_zynqmp_virt_defconfig'

  check:
    uses: analogdevicesinc/u-boot/.github/workflows/checks.yml@ci
