name: U-Boot CI

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build_arm:
    uses: analogdevicesinc/u-boot/.github/workflows/build-arm.yml@ci
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc594-som-ezkit-spl_defconfig'

  build_aarch64:
    uses: analogdevicesinc/u-boot/.github/workflows/build-aarch64.yml@ci
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc598-som-ezkit-spl_defconfig'
          - 'xilinx_zynqmp_virt_defconfig'

  check:
    uses: analogdevicesinc/u-boot/.github/workflows/checks.yml@ci
