name: U-Boot CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "adi-u-boot-2025.10.y" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_arm:
    uses: analogdevicesinc/u-boot/.github/workflows/build-arm.yml@ci
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc573-ezlite_defconfig'
          - 'sc584-ezkit_defconfig'
          - 'sc589-ezkit_defconfig'
          - 'sc589-mini_defconfig'
          - 'sc594-som-ezkit-spl_defconfig'
          - 'sc594-som-ezlite-spl_defconfig'

  build_aarch64:
    uses: analogdevicesinc/u-boot/.github/workflows/build-aarch64.yml@ci
    with:
      defconfig: ${{ matrix.defconfig }}
    strategy:
      matrix:
        defconfig:
          - 'sc598-htol-spl_defconfig'
          - 'sc598-som-ezkit-spl_defconfig'
          - 'sc598-som-ezlite-spl_defconfig'
          - 'xilinx_zynqmp_virt_defconfig'

  check:
    uses: analogdevicesinc/u-boot/.github/workflows/checks.yml@ci

  deploy_cloudsmith_checks:
    needs: [build_arm, build_aarch64, check]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      artifacts: >
        u-boot-*
